### ISSUE TITLE
Android Sample handshake error

### ISSUE THREAD

**Issue by naiyizhang** [WhatsApp/WhatsApp-OTP-Sample-App#4]
In this document,https://developers.facebook.com/docs/whatsapp/business-management-api/authentication-templates#---3,when handshake,  should put _ci_ param to intent, the _ci_ is PendingIntent pi = PendingIntent.getActivity() , int the Andorid sample , the _ci_ is PendingIntent.getBroadcast(), so which one is right?

**Comment by lucasfrossard** [comment]
Both will work.
